version: "2.24.3"
services:
  postgres:
    image: postgres
    container_name: postgres_c
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: osimseder
      POSTGRES_USER: root
      POSTGRES_PASSWORD: n1sWTx7hf9TWI7j
    volumes:
      # - ./postgres:/app
      # - database:/app/postgres
      - ./postgres:/var/lib/postgresql/data 
      - database:/var/lib/postgresql/data
  postgres-test:
    image: postgres
    container_name: postgres_test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: osimseder-test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: n1sWTx7hf9TWI7j
    volumes:
      # - ./postgres:/app
      # - database:/app/postgres
      - ./postgres:/var/lib/postgresql/data 
  server:
    build: ./server
    container_name: server_c
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PGUSER=root
      - PGHOST=127.0.0.1
      - PGDATABASE=osimseder
      - PGPASSWORD=n1sWTx7hf9TWI7j
      - PGPORT=5432
  client:
    build: ./client
    container_name: client_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /client/node_modules
    
#volumes for db
volumes:
  database: 