version: "2.24.3"
services:
  postgres:
    image: postgres
    container_name: postgres_c
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: osimseder
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      # - ./postgres:/app
      # - database:/app/postgres
      - ./postgres:/var/lib/postgresql/data 
      - database:/var/lib/postgresql/data
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #         - "5050:80"
  server:
    build: ./server
    container_name: server_c
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PGUSER=root
      - PGHOST=127.0.0.1
      - PGDATABASE=osimseder
      - PGPASSWORD=password
      - PGPORT=5432
  client:
    build: ./client
    container_name: client_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /client/node_modules
    
#volumes for db
volumes:
  database: 